### PR TITLE
fix angular-pdf: patch issue #67

### LINKED ISSUE #67: Page attribute doesn't work
There is a issue with page attribute, whatever you do is overwritten to page one when the directive is initialized, you can see it in the example of the project.

### PR DESCRIPTION
**Pull request by simobasso**
- [X] use more verbose `pageToDisplay` instead `pageNum`
- [X] on init use `pageToDiplay` instead 1
- [X] add a check on parse the attrs to ensure it's an int (else fallback to 1)

fix #67

### CODE REVIEW

**Comment by simobasso** [comment]
@sayanee can you review this?

**Comment by sayanee** [comment]
Had a brief look at the code without running it. 

I think it's better to keep it as `pageNum` as renaming it would be not be backward compatible and it will be a major version upgrade according to [sermver](http://semver.org/). `pageNum` is used in the view files when we declare `ng-model="pageNum"`. 

Let's rename it back to `pageNum`? :relaxed:

**Comment by simobasso** [comment]
@sayanee that part is unchanged, it's full backward compatible. 

`pagNum` it's used for the form, `pageToDisplay` for the pdf engine. (view files untouched)

**Comment by sayanee** [comment]
You are correct @simobasso - I just tried it as well.

**Pull request merged**
