### PR TITLE
Fix blur caused by fractional pixel dimension

### PR DESCRIPTION
**Pull request by ElRoberto538**
Here's the pull request for making sure the pixel dimensions are in whole numbers for the canvas size, unfortunately I was unable to replicate the blur issue at home as I only have a retina screen there and it seems to work fine that.

Here is an example of a PDF that was blurry on a 1080p screen when the pixels weren't whole numbers: http://www.nationalasthma.org.au/uploads/content/341-SMART-Asthma-Action-Plan-Rapihaler-only-English.pdf.

### CODE REVIEW

**Comment by sayanee** [comment]
Thanks! I will test it by this weekend. Do you have a screenshot of how it looks now so that I can compare with mine?

**Comment by ElRoberto538** [comment]
The Image below shows what a section of the PDF looks like - The left side is without this change, the right side is how it looks with the change.

fuzzy

Thanks!

**Comment by rwwagner90** [comment]
@ElRoberto538 shouldn't the Math.floor be used for both style and dimensions?

Currently you have:

```js
canvas.width = w * ratio;
canvas.height = h * ratio;
canvas.style.width = Math.floor(w) + 'px';
canvas.style.height = Math.floor(h) + 'px';
```

But why not do it for everything like so?

```js
canvas.width = Math.floor(w) * ratio;
canvas.height = Math.floor(h) * ratio;
canvas.style.width = Math.floor(w) + 'px';
canvas.style.height = Math.floor(h) + 'px';
```

Perhaps when the multiplication with the ratio occurs it ends up evening out or perhaps I have no idea what I'm talking about at all :smile: , but that was my only question about this.

**Comment by ElRoberto538** [comment]
@rwwagner90 I thought of that too, but found that browsers automatically truncate the width and height properties of the canvas so I thought it might be redundant.

**Comment by rwwagner90** [comment]
@ElRoberto538 even though the browsers might handle it already, I think for consistency it would be best to do `Math.floor` to all values. Would you mind updating that?

**Comment by ElRoberto538** [comment]
@rwwagner90 No problem, pull request updated now.

**Comment by rwwagner90** [comment]
@ElRoberto538 have you tested it on retina and non-retina and confirmed everything looks good?

**Comment by ElRoberto538** [comment]
@rwwagner90 Yep, works on both (1080p and retina Macbook)

**Comment by rwwagner90** [comment]
Okay, sounds good. Merged!

**Comment by sayanee** [comment]
Thanks @ElRoberto538 and @rwwagner90 - will publish this to bower by this week with a version upgrade :smiley:

**Comment by sayanee** [comment]
Thanks once again @ElRoberto538 and @rwwagner90! Now we can `bower i angular-pdf` with the [latest version 1.2.0](https://github.com/sayanee/angularjs-pdf/releases/tag/1.2.0) :tada: 

I also added @ElRoberto538 as a contributor in the spirit of [Open Open Source Project](https://github.com/sayanee/angularjs-pdf/blob/master/CONTRIBUTING.md#angular-pdf-is-an-open-open-source-project) :dancer: :dancers:

**Pull request merged**
