### PR TITLE
Add attribute to limit the canvas-height to its container

### LINKED ISSUE #127: Canvas does not restrict itself to maximum height
It does not currently seem possible to limit the height of the canvas element. In our case (openslides/OpenSlides#2097), we use angularjs-pdf to show a PDF fullscreen. In that case, `page-fit` should not only look at the width of the element, but also at the height.

Suggestion: Either make a different scaling type `page-fill` that behaves like the current `page-fit`, and change the behavior of `page-fit` (difficult due to backwards compatibility), or make a new attribute `limitHeight` (or similar) that changes this behavior.

I do have a patch ready with the latter suggestion.

### PR DESCRIPTION
**Pull request by lesteenman**
This patch adds an attribute that, combined with `scale='page-fit'`,
allows to fit the contents inside of the page both with respects to the
width and with respect to the height. Think of it as using
`background-size='contain'` rather than the default behavior of
`background-size='cover'` that `scale='page-fit'` triggers.

Fixes #127.

### CODE REVIEW

**Comment by lesteenman** [comment]
WIP: Pushed too early.

**Comment by lesteenman** [comment]
Note: It seems that even the cleanly pulled branch does not pass the tests, with the same error I'm getting here. However, I see that Travis still says your own builds are passing. Am I doing something wrong?

**Comment by sayanee** [comment]
Thanks @lesteenman - I haven't look at this in detail, but could you see some instructions on `[CONTRIBUTING.md](https://github.com/sayanee/angularjs-pdf/blob/master/CONTRIBUTING.md)` to run some tests / build locally with `grunt` and `npm`? That might give you some clue hopefully!

**Comment by lesteenman** [comment]
Yes, I have. I'm having no issues with steps 1-4. However, when I run `npm run build`, I'm getting the following error:

```
Running "karma:unit" (karma) task
11 05 2016 12:32:43.285:INFO [karma]: Karma v0.13.22 server started at http://localhost:9876/
11 05 2016 12:32:43.298:INFO [launcher]: Starting browser PhantomJS
11 05 2016 12:32:43.682:INFO [PhantomJS 1.9.8 (Linux 0.0.0)]: Connected on socket /#EIIhO8EZAS2tWGgcAAAA with id 34226259
PhantomJS 1.9.8 (Linux 0.0.0) ERROR
  TypeError: '[object Uint8Array]' is not a valid argument for 'Function.prototype.apply' (evaluating 'argsArray[i]')
  at /home/erik/projects/angularjs-pdf/example/js/lib/pdf.js:4519
PhantomJS 1.9.8 (Linux 0.0.0): Executed 2 of 4 ERROR (0.948 secs / 0.013 secs)
Warning: Task "karma:unit" failed. Use --force to continue.
```

Note that this same error occurs with a clean clone of your repository, and the same error occurs with the Travis CI build.

**Comment by lesteenman** [comment]
Updating `karma-phantomjs-launcher` to `^1.0.0` (from `^0.2.1`) seems to have worked. I'll submit a new PR.

**Comment by lesteenman** [comment]
This new version does not include `phantomjs-prebuilt` anymore. Adding a commit to include this dependency manually.

**Comment by dennybiasiolli** [comment]
@lesteenman can you please rebase this PR? Now the problems with tests should be resolved.

**Comment by lesteenman** [comment]
The earliest I can do that is next Tuesday, probably. If there is a deadline before then, please do so yourself; the changes should be straightforward.

**Pull request closed without merging**
