### PR TITLE
File loading experience

### PR DESCRIPTION
**Pull request by timtos**
* Clear the canvas before loading a new file (otherwise one will see the old document until the new document gets loaded. On slow connections this can be very nasty.)
* Abort page load/ render process if another page gets loaded
*  Abort (destroy) current document loading when a new document gets loaded

### CODE REVIEW

**Comment by sayanee** [comment]
Thanks for your pull request @timtos :smiley: Could you please help to do a couple of things:

1. Remove the [git conflict markers on lines `154`, `159` and `162`](https://github.com/timtos/angularjs-pdf/blob/FileLoadingExperience/example/js/directives/angular-pdf.js#L154-L162)
- Send a pull request to the file `dist/angular-pdf.js` instead. Here's the [contributing guidelines](https://github.com/sayanee/angularjs-pdf/blob/master/CONTRIBUTING.md).

**Comment by timtos** [comment]
Hey @sayanee. Sorry for the conflict markers. I removed them. Unfortunately I don't know how to fulfil your seconds point "Send a pull request to the file dist/angular-pdf.js instead." Do you mean that there should be only one commit in the branch and if there are more one should use amend?

**Comment by timtos** [comment]
@sayanee, now I see the whole mess I created. Your last update came unexpected. I will try to get things straight again... Sorry for this.

**Comment by timtos** [comment]
Done. :)

**Comment by sayanee** [comment]
Thanks for your contribution @timtos! 

In the spirit of [open open source](https://github.com/sayanee/angularjs-pdf/blob/master/CONTRIBUTING.md#angular-pdf-is-an-open-open-source-project) I added you to the contributors list :star2:

**Comment by timtos** [comment]
Hey @sayanee, thanks a lot. I'll handle the open open source spirit with care.

**Pull request merged**
