### PR TITLE
feat(*): allow AMD and CommonJS integration

### PR DESCRIPTION
**Pull request by boyanin**
Allow the file to be loaded as a module, using AMD or CommonJS.

### CODE REVIEW

**Comment by simobasso** [comment]
Hi @boyanin!

thanks for PR!

What do you think about #163 ?

**Comment by dennybiasiolli** [comment]
Hi @boyanin,
Thanks for your PR, we are currently testing #163 and I think that the module implementation will be already included during webpack's build process.
Would you like to help us testing that PR, verifying the modularity of the build?
Thanks for your help, this PR is in testing and will be merged in a few days. :)

**Comment by boyanin** [comment]
Hi @dennybiasiolli and @simobasso . It looks great with #163 I came along your lib today and decided to extend with this modularity. I'd be happy to hel you testing it according to es6. Let me know how I can contribute :)

**Comment by dennybiasiolli** [comment]
Thanks @boyanin , you can find `es6` PR in [this repo](https://github.com/simobasso/angularjs-pdf.git) and checkout `es6` branch.
This branch has a lot of improvements, so we are testing in depth before merging into master.
Thanks a lot for your help :)

**Comment by simobasso** [comment]
closed in favor of #184 (thx @boyanin anyway)

**Pull request closed without merging**
