### PR TITLE
Support retina canvas

### LINKED ISSUE #53: PDF fuzzy on retina
I already have fixed this locally, so I can submit a PR, if you'd like. You're welcome to fix it yourself if you would rather too.

### PR DESCRIPTION
**Pull request by rwwagner90**
Resolves #53

### CODE REVIEW

**Comment by rwwagner90** [comment]
Any feedback for this PR @sayanee ? I'd be glad to make changes if I need to.

**Comment by sayanee** [comment]
i'm so sorry - will do so by weekend!

**Comment by sayanee** [comment]
:tada: Released! Thank you so much :star2: 

Added you as a [contributor](https://github.com/sayanee/angularjs-pdf#contribute) as according to the [open open source model](https://github.com/Level/community/blob/master/CONTRIBUTING.md)

**Comment by rwwagner90** [comment]
Okay, awesome. Thanks :smile:

**Pull request merged**
