### PR TITLE
Add scope password callback handler

### PR DESCRIPTION
**Pull request by guicoma**
I believe the title is quite self-explanatory.
I'm not sure if the changes I made are valid since the build and unit test gave me a "weird error".

`Aborted due to warnings.`
`npm ERR! weird error 3`
`npm WARN This failure might be due to the use of legacy binary "node"`

### CODE REVIEW

**Comment by sayanee** [comment]
Hi! Would you be able to pass the continuous integration tests? Also have a read through the [contributing guidelines](https://github.com/sayanee/angularjs-pdf/blob/master/CONTRIBUTING.md) - you only need to amend file `dist/angular-pdf.js` and run `npm run build`

**Comment by guicoma** [comment]
Hi there,
I tried to run to build task, however I seem to have trouble with this `weird error 3` (as I stated in my first comment, I've been looking into it but I haven't found the solution yet).

I thought that running `npm run build` would ammend the `dist/angular-pdf.js` file. Am I supposed to change something manually?

Thanks

**Comment by sayanee** [comment]
If you are submitting a patch to this repository (and not a fork) then you need not amend `package.json` and `bower.json`. 

Yes, unsure about the errors too.

**Comment by dennybiasiolli** [comment]
Password callback handler added to version 1.4.0 ;)

**Pull request closed without merging**
